# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.0
  aws-ecr: circleci/aws-ecr@8.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: ./api
          push-image: true
          registry-id: AWS_ECR_REGISTRY_ID
          repo: 'joealdproj-api'
          tag: '${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - main
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: ./web
          push-image: true
          registry-id: AWS_ECR_REGISTRY_ID
          repo: 'joealdproj-web'
          tag: '${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - main
