# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.0
  aws-ecr: circleci/aws-ecr@8.1.0
  aws-ecs: circleci/aws-ecs@2.2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_and_deploy_api:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - aws-ecr/build-and-push-image: # Use the pre-defined `build-and-push-image` job
          dockerfile: Dockerfile
          path: /api
          repo: '${API_PREFIX}-api'
  build_and_deploy_web:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - aws-ecr/build-and-push-image: # Use the pre-defined `build-and-push-image` job
          dockerfile: Dockerfile
          path: /web
          repo: '${API_PREFIX}-web'
          
workflows:
  build-and-deploy:
    jobs:
      - build_and_deploy_api
      - build_and_deploy_web:
          requires:
            - build_and_deploy_api
      - aws-ecs/deploy-service-update:
          requires:
            - build_and_deploy_api
            - build_and_deploy_web
          family: '${APP_PREFIX}-service'
          cluster-name: '${APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${APP_PREFIX}-service'
      
